### ISSUE TITLE
Black-screen (WebView Chrome 72+)

### ISSUE THREAD

**Issue by Lakaroth** [AltimitSystems/mv-android-client#8] opened 2019-02-02 15:58 UTC
Dear felixjones i find an issue...
I have update Android Studio, after that i got this:
`WARNING: The specified Android SDK Build Tools version (27.0.3) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.3.0.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '27.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
Remove Build Tools version and sync project
Affected Modules: app`
 It seems like compile has been deprecated and api or implementation should be used instead. According to [The Java Library Plugin - Gradle User Guide Version 3.5](https://docs.gradle.org/current/userguide/java_library_plugin.html):
The compile configuration still exists but should not be used as it will not offer the guarantees that the api and implementation configurations provide.

So i've change compile to implementation:
In Module app:
This 
![image](https://user-images.githubusercontent.com/47223252/52164076-f0c31e80-26eb-11e9-915d-d6b76ddee5bf.png)

To this:
![image](https://user-images.githubusercontent.com/47223252/52163989-fb30e880-26ea-11e9-9b66-2650f2d7e525.png)
After doing i've update my app on playstore, everything was fine untill some users got a black screen, only Samsung S9 or S9+ with Android 8.0.0
On google play console pre launch app, i find out the problem:
![image](https://user-images.githubusercontent.com/47223252/52164016-30d5d180-26eb-11e9-8529-95a353d4d77d.png)
I've read in some case, on Implementation you'll have to provide content labels.
I think is in manifest file (i'm not a programmer)
How to fix this?
Thank you.
PS: [here a screen](https://www.gameovercarrara.it/extra/bugs/samsunganomaly.png) with system info of 4 Samsung S9+ (2 working 2 not working) it's reallly strange.

**Comment by felixjones** [comment] 2019-02-02 16:30
The gradle files have been using implementation since commit **3ecc1f3a4101f71674ee94dc3c6a322f4e0316d7** March 13th 2018, so you're using an old version of MV Android Client. Please use the latest version.

Regardless, that warning is merely a warning and is unrelated to the black screen that you have. Could you please copy your logcat output of this (available in Android Studio when phone is connected and game is running in debug mode).

It's not strange that 2 Samsung devices work whilst 2 don't: Samsung devices are notoriously quirky, they have different hardware depending on the region they're bought in and some of those configurations are infamous for their misbehaving GPUs/drivers.

Do you use any Plugins? Is this CrossWalk or WebView?

**Comment by Lakaroth** [comment] 2019-02-02 16:50
Hi thanks for your answer, i have tested on my Xiaomi where it works, unfortunately i don't have the Samsung S9 to test it.
The logcat file is really long i past it into a txt fil,  hope is correct.
[logcat.txt](https://github.com/AltimitSystems/mv-android-client/files/2824627/logcat.txt)
I use these plugins:
![plugins](https://user-images.githubusercontent.com/47223252/52166831-b620ac80-2712-11e9-901c-a419e1588b6d.png)
My RMMV and Project versions: 1.5.1
i use WebView.
If a samsung S9 is needed for the bug, i can find one for test and update the logcat.txt, just tell me if the logcat that i've upload here is correct.
Thank you for your time.

**Comment by felixjones** [comment] 2019-02-02 16:58
I need the logcat for a device that shows this bug, any other logcat is useless as there's something in particular I want to look with the black-screen.

I already have a theory for what your problem is, but I need a logcat to confirm it. Also in the future with logcats you can select "Show only selected application" as a filter so the logcat only shows the output for your game, not your entire phone (which is why your one is so big).

**Comment by Lakaroth** [comment] 2019-02-02 17:03
Ok thank you i'll find a Samsung S9 and i'll send you the correct Log.
'm sure i have  check "Show only selected application" but it give me back a lot of text!
So, thank you for now.

**Comment by felixjones** [comment] 2019-02-03 14:51
Please do not select "Errors", it must be "Verbose". What I am looking for is not an Error, it's information output

**Comment by Lakaroth** [comment] 2019-02-03 15:42
Sorry, here the verbose logcat.
(Even if i select "Errors and Show only selected application". when i plug the mobile it start write a lot of stuff i don't understand!
![image](https://user-images.githubusercontent.com/47223252/52178695-eed38b00-27d1-11e9-974f-0f74b16da6a1.png)

Anyway it's here, Old Mv Client (Ps i've change app name cause installations problem but it's that)
[logcat_verbose.txt](https://github.com/AltimitSystems/mv-android-client/files/2825650/logcat_verbose.txt)
New MV Client
[logcat_verbose_NewMVClient.txt](https://github.com/AltimitSystems/mv-android-client/files/2825659/logcat_verbose_NewMVClient.txt)

Thanks you again!

**Comment by felixjones** [comment] 2019-02-03 16:04
It's because you have no debuggable process (in red) - did you not launch your game via debug run in Android Studio?

Anyway, looking at the logcat it's not even getting far enough to load Pixi.js which suggests a bug in Samsung's flavour of Android. I will need to investigate, if I send you instructions for modifying the code would you be happy to do that?

**Comment by Lakaroth** [comment] 2019-02-03 16:07
Sorry for my less skills on Android Studio, i feel this like a nightmare because i can't understand how to fix it.
Thank for your help i will be happy to do every modify needed to fix this...

PS: From android studio i'll do RUN > Debug App (With device connected) it is wrong?

**Comment by felixjones** [comment] 2019-02-05 22:00
Fixed with 741198303a7f77037d9031a82cc9e228687448f9

**Closed by felixjones** 2019-02-05 22:00 UTC
Labels: bug, webview issue

**Comment by Lakaroth** [comment] 2019-02-05 22:02
Fantastic!
Thank you!
What was the cause? if i can ask.
I'm really curios.

**Comment by felixjones** [comment] 2019-02-05 22:11
I'm still not 100% sure what the cause was, but apparently Chrome 72 dislikes raw HTML data sent to it when decoded from a Base64 string (even though those two processes are entirely, completely, 100% separate and don't interact).

loadData supports base 64 string decoding anyway, so I removed the manual decode and used the WebView one (should make loading games a micron faster, too).

**Comment by Lakaroth** [comment] 2019-02-05 22:24
i got an email from google dev about this... i'll send you if you want.
I'm not sure you read this email cause you delete the post.
If yes, send me your email i'll send you the google disclaimer about 64bit
app's new law

Il giorno mar 5 feb 2019 alle ore 23:11 Felix Jones <
notifications@github.com> ha scritto:

**Comment by felixjones** [comment] 2019-02-05 22:34
MV Android Client with WebView is already 64 bit
